image: node    # Run the job in a `node` docker image

stages:
  - build
  - deploy

build:
  stage: build
  cache:
    paths:
      - node_modules/
  script:
    - echo "Installing"
    - CI=false npm install
    - echo "building"
    - CI=false npm run build 
    - echo "Build successful"

  artifacts:
    paths:
      - build/          # Save the build result as an artfact

test:
  stage: test
  cache:
    paths:
      - node_modules/
    policy: pull
  script:
    - npm run test


pages:
  stage: deploy
  dependencies:
    - build
  script:
    - rm -rf public
    - cp build/index.html build/404.html
    - mv build public
  artifacts:
    paths:
      - public
  only:
    - master
  
 
  

