stages:
  - build

build:
  image: node    # Run the job in a `node` docker image
  stage: build
  script:
    - npm install      # Run `npm install` and `npm build`
    - npm build
  artifacts:
    paths:
      - build/          # Save the build result as an artfact
